### ISSUE TITLE
Electra Finetune on HLGD + Time, Model weights usage

### ISSUE THREAD

**Issue by badrinath-newzera** [tingofurro/headline_grouping#1]
Do we need to add some layers(768x1 and 2x2) and train, as mentioned in the paper? Or we can use classifier_electra_hlpc_1_f1_0.7442.bin directly to classify?
If we can use it directly, then can you please send a sample code?

Thanks

**Comment by tingofurro** [comment]
Hello Badrinath,

Good question! I've added a script that gives an example of how to use the model: [model_classifier.py](https://github.com/tingofurro/headline_grouping/blob/main/model_classifier.py).

Note: I've also renamed the classifier model file to `cls_elec_base_hlgd_0.74f1.bin`, but it is the same that was uploaded previously.
